### ISSUE TITLE
error in strict mode

### ISSUE THREAD

**Issue by daniran** [lokesh/color-thief#102]
The code breaks when running in strict mode.
In line 274 there is a variable `index` that is not defined.
[https://github.com/lokesh/color-thief/blob/master/src/color-thief.js#L274](https://github.com/lokesh/color-thief/blob/master/src/color-thief.js#L274)
Since I concat all my libs under one file, I cannot use this unless strict mode works.

**Comment by daniran** [comment]
in fact, the `index `variable appears in several functions.
I'm assuming it is supposed to be some library-level variable?
Currently it's sitting on `window.index`

**Comment by Deepblue129** [comment]
+1

**Comment by skitterm** [comment]
Wonder if it's related to this? https://github.com/jariz/vibrant.js/issues/20

**Comment by tatemz** [comment]
Any update on this?

**Comment by lokesh** [comment]
The original issue with the undefined `index` variable was resolved.
