### ISSUE TITLE
Use ColorThief with an image proxy

### ISSUE THREAD

**Issue by Shade-** [lokesh/color-thief#106]
Hi,
I thought this would be useful for others stuck with CORS-related issues on domains they don't have any kind of control on. You can wrap external images within Google's proxy server, which supports CORS requests.

Eg.:

``` javascript
var source = 'EXTERNAL IMAGE LINK', image = new Image(), dominantColor;
image.crossOrigin = 'Anonymous';
image.src = 'https://images1-focus-opensocial.googleusercontent.com/gadgets/proxy?container=focus&refresh=2592000&url=' + encodeURIComponent(source);

$(image).on('load', function() {
    var thief = new ColorThief();
    dominantColor = thief.getColor(image);
});
```

It may be a little bit slower but it works. You need jQuery to use the load event on the image, but you can easily adapt it to VanillaJS. It is necessary because ColorThief needs the image dimensions which are determined only when the image has been downloaded.

**Comment by Simingchen** [comment]
i get it

**Comment by lokesh** [comment]
I added a section on the demo page's FAQ that goes over this technique. Thanks for sharing. 👏 
https://lokeshdhakar.com/projects/color-thief/#faq
