### ISSUE TITLE
Is this still supported?

### ISSUE THREAD

**Issue by jpruiz114** [lokesh/color-thief#107]
I can't even install the package via npm install.

**Comment by ItamarShDev** [comment]
Want to know too

**Comment by mariotacke** [comment]
Looks like there is a fork on npm from null2 (https://github.com/null2/color-thief) which publishes to npm. Unfortunately, that fork has a dependency on `canvas` which does not work in my scenario. You can fork the project and add a `module.exports = ColorThief` to the color-thief.js file. This lets you require it.

**Comment by earthbound19** [comment]
This is clearly not maintained anymore. There are many outstanding pull requests including from three years ago. And it's forked all over github. @mariotacke do the steps you mention get it working?

**Comment by mariotacke** [comment]
Yup. I actually forked it myself (https://github.com/mariotacke/color-thief) and released it on npm (https://www.npmjs.com/package/@mariotacke/color-thief) as a scoped package.

**Comment by bernatfortet** [comment]
@mariotacke 
I'm getting this error when using your package:
```
TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(CSSImageValue or HTMLImageElement or SVGImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap or OffscreenCanvas)'
```
Any idea?

**Comment by mariotacke** [comment]
@bernatfortet, unless you show some of your code using my forked package I won't be able to help you. Also, please open a new issue on the forked project if you believe your problem is related to it specifically. I do not intend to take over development, I simply wrapped the existing color thief to make it work in our app.

**Comment by bernatfortet** [comment]
@mariotacke I just figured it out.
It turns out that the image has to be an HTML element instead of a url.

Thanks

**Comment by gbrits** [comment]
Meh. Use https://github.com/briangonzalez/jquery.adaptive-backgrounds.js instead.

**Comment by gbrits** [comment]
If you want a solution that makes the background go a certain color, look here:
https://github.com/briangonzalez/jquery.adaptive-backgrounds.js

**Comment by lokesh** [comment]
Sorry for lack of visibility and updates. I've recently ramped back up on the project. I'm working on additional docs and supporting Node w/o the heavy deps of [null2's fork](https://github.com/null2/color-thief).

re: modules
- The module has been published to npm under `colorthief` (no dash)
- CommonJS, AMD, and ES6 module support was added in latest release: https://github.com/lokesh/color-thief/releases/tag/2.2.0

--
It wasn't supported. But it is again now.

**Comment by ItamarShDev** [comment]
@lokesh will be happy to help with the new road map.
I think that opening issues for features would help getting PRs

**Comment by lokesh** [comment]
One more update for this thread about recent work and the roadmap.

- Node support just added in v2.3.0: https://github.com/lokesh/color-thief/releases/tag/v2.3.0
- Next, I'm fleshing out the docs to be more complete. I'm also triaging the issues and outlining a roadmap. I will put a call out at this time for some help, especially related to the build process which is quite clunky and full of manual steps at this time.

More to come.

**Comment by ItamarShDev** [comment]
Will be happy to help

**Comment by liquidvisual** [comment]
I'm having all sorts of errors trying to `npm install color-thief` in 2020 with Node v14.9.0 :(
