### ISSUE TITLE
var needed for the source code

### ISSUE THREAD

**Issue by leijing7** [lokesh/color-thief#111]
At line 277 there needs a 'var' as 

```
var index = getColorIndex(i,j,k);
```

**Comment by AlfredJKwack** [comment]
My IDE stays...

<img width="846" alt="screenshot 2018-12-02 at 17 59 51" src="https://user-images.githubusercontent.com/557102/49342480-1edca180-f65c-11e8-88db-3c6ea8af9bd7.png">

So let us assume things are as good as they're going to get until @lokesh decides which linting rules should be added to the library's config.

**Comment by lokesh** [comment]
Closing out old issues.

Decided to go with eslint eventually. https://github.com/lokesh/color-thief/pull/151
