### ISSUE TITLE
How can i convert your color palette to mine

### ISSUE THREAD

**Issue by mihdan** [lokesh/color-thief#116]
How can i convert your color palette to mine that looks like this      

`var colors = [ '#ff0000 ', '#00ff00 ', '#0000ff ' ];`

**Comment by zamartz** [comment]
I have a fix suggested - here https://github.com/lokesh/color-thief/pull/78 - make sure you like or comment on the post so it goes into the main branch

**Comment by lokesh** [comment]
The original issue need more clarification. The first linked in #78 might or might not be related. As a side note, long overdue, but I'm looking to merge the hex support feature in.
