### ISSUE TITLE
Save cluster colors

### ISSUE THREAD

**Issue by benstadin** [lokesh/color-thief#119]
Would be great if there was an option to save the image back using clustered colors like here (image with the guy in t_shirt):
https://making.lyst.com/2014/02/22/color-detection/

**Comment by AlfredJKwack** [comment]
leeoniya already has:
https://gist.github.com/nrabinowitz/1104622/fee9aa3f51b22c2dc468ef754d6032f53d4700af#gistcomment-804264

**Comment by lokesh** [comment]
Closing out older issues. This isn't on the roadmap.
