### ISSUE TITLE
get error on ubuntu 16.04

### ISSUE THREAD

**Issue by roysG** [lokesh/color-thief#121]
> canvas@1.2.11 install /var/www/selfie/selfiecash/server/node_modules/color-thief/node_modules/canvas
> node-gyp rebuild

./util/has_cairo_freetype.sh: 4: ./util/has_cairo_freetype.sh: pkg-config: not found
gyp: Call to './util/has_cairo_freetype.sh' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:354:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-71-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /var/www/selfie/selfiecash/server/node_modules/color-thief/node_modules/canvas
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

**Comment by kiqs** [comment]
I have the same issue on Mac

**Comment by madelinecameron** [comment]
You are missing dependencies. 

`sudo apt-get install libcairo2-dev libjpeg-dev libgif-dev`

**Comment by lokesh** [comment]
@roysG This has to do with the `canvas` dependency. See Ubuntu requirements: https://github.com/Automattic/node-canvas/wiki/Installation---Ubuntu-and-other-Debian-based-systems

For OSX/Mac you can find detailed instructions here:
https://github.com/Automattic/node-canvas/wiki/Installation---OSX

If you have Homebrew installed than you can try the following:
`brew install pkg-config cairo libpng jpeg giflib`
