### ISSUE TITLE
IE11 and SVG

### ISSUE THREAD

**Issue by H1D** [lokesh/color-thief#123]
Seems like ColorThief simply doesn't work with with with IE11 and SVG. It fails with `SecurityError` on this line – https://github.com/lokesh/color-thief/blob/master/src/color-thief.js#L52

What I found about it – https://stackoverflow.com/questions/20322745/ie-throws-security-error-when-calling-todataurl-on-canvas

**How to reproduce**
1) Open demopage in IE11 http://lokeshdhakar.com/projects/color-thief/
2) press F12 to see errors
3) drop any SVG image

**Comment by AlfredJKwack** [comment]
Thanks for highlighting this. 

I don't think this will be fixed since - as noted in your helpfully supplied stackoverflow question - this is a bug of IE11.

**Comment by lokesh** [comment]
There are no plans for future IE11 work. Closing.
