### ISSUE TITLE
Need to reload page before take effects

### ISSUE THREAD

**Issue by BenjaminHoegh** [lokesh/color-thief#127]
For some reason I need to reload the page before it get the dominated color when change image. why that?

HTML
```
<img src="images/6.jpg" id="myimg">
<div id="mydiv"></div>
```

JS
```
$(function(){
    var image = $("#myimg").get(0);
    var colorThief = new ColorThief();
    var color = colorThief.getColor(image);
    $("#mydiv").css("background-color", "rgb(" + color + ")"); 
});
```

**Comment by AlfredJKwack** [comment]
Hi,

Could you define 'when change image'? Are you loading new images with JS (as in a carousel) or something like that?

**Comment by HawkonDK** [comment]
New image like I change the image in the HTML.

How many github projects are you working on??  😂

**Comment by AlfredJKwack** [comment]
Sounds to me like the JS is firing before the image is loaded. On refresh the browser just picks it from the cache.

**Comment by lokesh** [comment]
Closing out older issues.

The original issue was likely related to the `getColor()` method being called ahead of the image being finished loading. 

I'm looking to make a breaking change in v3 that will always have the `getColor()` method return a promise and wait for the image load if it is in progress for the user.
