### ISSUE TITLE
I simply cannot get this to work, no matter the source of the image (The canvas has been tainted by cross-origin data)

### ISSUE THREAD

**Issue by teenangst** [lokesh/color-thief#128]
No matter if the image is in the same place as the javascript and html - I get a an error
```
color-thief.min.js:18 Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.
```

I am using this which seems to work for other people but does not work for me:
```
var image = document.querySelector('#img');
image.onload = function(){
    var colorThief = new ColorThief();
    var color = colorThief.getColor(image); 
   console.log(color);
};
```

What do I have to do to make this work at all?

**Comment by teenangst** [comment]
Update, just built a php ajax api for this which will be more stable and faster anyway; this is no longer urgent.

**Comment by danielehrhardt** [comment]
Can you send you code?

**Comment by moizmb** [comment]
@teenangst Could you post a snippet of the code that worked for you

**Comment by danielehrhardt** [comment]
do it simply like this :)
```
var img = document.createElement('img');
    img.setAttribute('crossOrigin', '');
    img.setAttribute('src', this.data.src.small)
    img.addEventListener('load', () => {
        var vibrant = new Vibrant(img);
        var swatches = vibrant.swatches()
        for (var swatch in swatches)
            if (swatches.hasOwnProperty(swatch) && swatches[swatch])
                this.colorPalette.push({hex: swatches[swatch].getHex()})
    });
```

**Comment by shuiRong** [comment]
I have the same error.(not on a http-server)
It's ok , if i use `http-server` to run the index.html.

**Comment by AlfredJKwack** [comment]
Ahem,

Browsers these days don't like you loading stuff straight from the filesystem. Here's [a good explanation of CORS](https://mobilejazz.com/blog/which-security-risks-do-cors-imply/) if you want to know more.

Try this or your local equivalent instead:

```
[me@macOs]$ cd ~/GitHubRepos/color-thief
[me@macOs]$ python -m SimpleHTTPServer 8000
[me@macOs]$ open http://localhost:8000
```

Good luck.

**Comment by th0rgall** [comment]
I had some success by using [this](https://stackoverflow.com/questions/37008314/failed-to-execute-getimagedata-the-canvas-has-been-tainted-by-cross-origin-d) StackOverflow answer and modifying the color-thief code on a [fork](https://github.com/null2/color-thief/) to set the following property after it initializes an Image().

Insert after [https://github.com/null2/color-thief/blob/master/js/color-thief.js#L55](https://github.com/null2/color-thief/blob/master/js/color-thief.js#L55)
```
img.crossOrigin = 'anonymous';
```

It works but I need to invoke the getColor() action a 2 times for it to work, and errors always occur the first time.

**Comment by AlfredJKwack** [comment]
@th0rgall 

Not sure if that would work with data urls.

```

if ( img.substring(0,5) !== 'data:' )
      img.crossOrigin = "Anonymous";

```

**Comment by AntiMoron** [comment]
Same here.

**Comment by lokesh** [comment]
Closing out the issue. I've added info on CORs issues to the demo page and fleshed out the docs: https://lokeshdhakar.com/projects/color-thief/#faq

If you are having trouble using the script still, check out the instructions on getting support:
https://lokeshdhakar.com/projects/color-thief/#support
