### ISSUE TITLE
Image with darken background gives bad result

### ISSUE THREAD

**Issue by jkcen** [lokesh/color-thief#134]
Hi, there,
 I like your project and it works great for pictures with light background. But when it comes to other pictures with darken background, it starts to give bad result far from expected. For example the follow two pictures (CC0 licensed), the color-thief works poorly to pickup the colorful hues from them. It would only pick up grey-to-dark while calling the lib. 
![brick-wall-1850095_1920](https://user-images.githubusercontent.com/22850016/36928129-db30ab0e-1e37-11e8-9528-80f5f070bb00.jpg)
![chair-558951_1920](https://user-images.githubusercontent.com/22850016/36928130-db48c1da-1e37-11e8-8a45-7e0b94c1a668.jpg)

Here is the code that I use:
```
img.onload = function(e) {
                    var can = document.createElement('canvas');
                    var ctx = can.getContext("2d");
                    ctx.drawImage(this, 0, 0, this.width, this.height);
                    var imageData  = ctx.getImageData(0, 0, this.width, this.height);
                    var colorThief = new ColorThief();
                    var pal = colorThief.getPalette(can);
                    console.log(pal);
};
```

However, the [demo ](http://lokeshdhakar.com/projects/color-thief/) works a bit better there. Why there is such a big difference on the demo page while compared to my own implementation?

Any ideas? 

Thanks!

**Comment by lokesh** [comment]
Older issue, but I'm investigating improvements into the color clustering algorithm so I thought I'd take a peek.

The results seemed reasonable for these two images. Not far off from what I expected:

![image](https://user-images.githubusercontent.com/51469/62753666-73bd8c80-ba21-11e9-8bd3-d5b2f39602ae.png)

![image](https://user-images.githubusercontent.com/51469/62753670-7d46f480-ba21-11e9-9bd1-9baf464102bf.png)
