### ISSUE TITLE
How can I integrate this with Google Sheets and Apps Script?

### ISSUE THREAD

**Issue by Jodastt** [lokesh/color-thief#141]
I have a [spreadsheet](https://docs.google.com/spreadsheets/d/1yfbszPNxeeRkIGzB8xF1woSR4xJRut6j2-HDr1sGN20/edit#gid=569426832) that has images generated by this equation: `=HYPERLINK("https://www.monstercat.com/release/"&Albums!S2,IMAGE(WIU!C7,4,195,195))`
How can I use this image as a variable in Google Apps Scripts then extract the color from _that_  image?

**Comment by lokesh** [comment]
Closing as this is mostly a Google Sheets questions and not about Color Thief.

If Google Sheets doesn't have a built-in method for grabbing the color from an image you would like have to host a service in an external location and pass in the image data and have it return the color values.
