### ISSUE TITLE
Error Installing Canvas

### ISSUE THREAD

**Issue by KyzaGitHub** [lokesh/color-thief#142]
### Error Installing Canvas

- Platform
  - Windows 10 x64
- NPM Version
  - 6.4.1
- Nodejs Version
  - v10.15.0
- color-thief Version
  -  v2.0.1

<details>
<summary>Stacktrace</summary>
<pre><code>C:\Users\[MY_NAME]\OneDrive\Websites\APIs>npm i color-thief

canvas@1.6.13 install C:\Users\[MY_NAME]\OneDrive\Websites\APIs\node_modules\color-thief\node_modules\canvas
node-gyp rebuild

C:\Users\[MY_NAME]\OneDrive\Websites\APIs\node_modules\color-thief\node_modules\canvas>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Program Files\Python36\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\[MY_NAME]\OneDrive\Websites\APIs\node_modules\color-thief\node_modules\canvas
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.6.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.6.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\[MY_NAME]\AppData\Roaming\npm-cache\_logs\2019-02-15T15_53_36_424Z-debug.log</code></pre>
</details>
<br>
<details>
<summary>Notes</summary>
<ul>
<li>It seems like the problem occurs when installing <code>canvas@1.6.13</code>.</li>
<li>The lastest version of <code>canvas</code> (here <code>canvas@2.3.1</code>) successfully installs on its own.</li>
<li><code>canvas@1.6.13</code> does not successfully install on its own.</li>
<li>I submitted this issue here since <code>color-thief</code> uses an old version of <code>canvas</code> and this problem seems to have been fixed since then.</li>
</ul>
</details>
<br>
<details>
<summary>Related Issues</summary>
<ul>
<li>#98</li>
<li>#69</li>
</ul>
</details>

**Comment by AlfredJKwack** [comment]
The NPM version is a fork.. https://github.com/null2/color-thief
The branch is 29 commits ahead, 35 commits behind lokesh:master.

**Comment by conanliuhuan** [comment]
you need to install python 2.7

**Comment by lokesh** [comment]
Sorry for confusion. For any future googlers who end up here, some clarification:

- This repo and project use the npm package name `colorthief`. Node env support was added in v2.3.0.
- The null2 fork https://github.com/null2/color-thief uses the npm package name `color-thief. It added node support first and is the one most people are installing as a dep in their project. If you need help installing deps for that project or have other issues with that package, you'll need to contact that project owner directly.

I've pinged null2 in hopes to resolve some of the naming confusion and merge the projects. 🤞
