### ISSUE TITLE
No need to attach canvas element to DOM

### ISSUE THREAD

**Issue by av01d** [lokesh/color-thief#148]
In the CanvasImage constructor, the `this.canvas` element is appended to `document.body`:
```
document.body.appendChild(this.canvas); 
```
A bit later, in the `getPalette` function, it is removed:
```
// Clean up
image.removeCanvas();
```

There is absolutely no need to attach the canvas element to the DOM.
In the constructor, leave this line out:
```
//document.body.appendChild(this.canvas); 
```
Then, remove the `CanvasImage.prototype.removeCanvas` function, and finally, omit the `image.removeCanvas()` call in the `getPalette` function.
Saves some code and doesn't touch the DOM. Color Thief still works as before.

**Comment by lokesh** [comment]
Released in v2.1.0 https://github.com/lokesh/color-thief/releases/tag/v2.1.0
