### ISSUE TITLE
Can we use this with React Native?

### ISSUE THREAD

**Issue by rabpeter** [lokesh/color-thief#149]

**Comment by lokesh** [comment]
I don't have experience with React Native so I cannot say for sure. Color Thief renders an HTML `<canvas>` tag in browser which it uses to get the pixel data for the image. If this is supported in React Native, it should work.

I'm looking into adding support for the Jimp JS library for the pixel data extraction for images and this will remove the need for rendering in a web view.

**Comment by deflexable** [comment]
any updates on this?
