### ISSUE TITLE
Keep CDN files up to date

### ISSUE THREAD

**Issue by RudeySH** [lokesh/color-thief#153]
https://cdnjs.com/libraries/color-thief

Currently, CDNJS only has Color Thief v2.0.1. While the Color Thief package published through NPM is already at v2.2.5.

**Comment by RudeySH** [comment]
It turns out there is no NPM package by lokesh. Apparently the version I was using is a fork. https://github.com/null2/color-thief

**Comment by lokesh** [comment]
The CDN is updated to include the latest version of this package, v2.3.0:
https://cdnjs.com/libraries/color-thief

There is a lot of confusion around the npm package name which I'm working to resolve.

This repo uses the name `color-thief`, but the npm package it is published as-is `colorthief`. The npm package with the dash, `color-thief`, is from the null2 fork.

So if you want to install this project as a dep via npm, you should use `colorthief`. But... you can still use the `color-thief` name from cdnjs which references this repo.
