### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by RudeySH** [lokesh/color-thief#154]
I'm using the latest version of Color Thief distributed by NPM, which is v2.2.5.

![image](https://user-images.githubusercontent.com/3918757/59413147-48bb1180-8dbf-11e9-9c81-b6115cd1acf3.png)

Color Thief doesn't work in browsers.

**Comment by RudeySH** [comment]
It turns out there is no NPM package by lokesh. Apparently the version I was using is a fork. https://github.com/null2/color-thief

**Comment by lokesh** [comment]
Sorry for confusion. For any future googlers who end up here, some clarification:

- This repo and project uses the npm package name `colorthief`. Node env support was added in v2.3.0.
- The null2 fork https://github.com/null2/color-thief uses the npm package name `color-thief. It added node support first and is the one most people are installing as a dep in their project. If you need help installing deps for that project or have other issues with that package, you'll need to contact that project owner directly.

I've pinged null2 in hopes to resolve some of the naming confusion and merge the projects. 🤞
