### ISSUE TITLE
Feature Request - Input Color as close value

### ISSUE THREAD

**Issue by bapfnet** [lokesh/color-thief#175]
Using color-thief for green-screen or blue-screen detection, sometimes the clothes or skin color of the person are more dominant than the background.

How about to give an input color e.g. #00FF00 for green to the function that it can look for the closest dominant color to the input value?

**Comment by lokesh** [comment]
Doing some clean-up on the repo.

Thanks for the suggestion but it's outside the goals of the library at this time. There is interest in showing the weight or percentage of usage of colors in an image. These features could be utilized to help w/background extraction though the library is not specifically planning on addressing the use case.
