### ISSUE TITLE
IE11 report TypeMismatchError Exception

### ISSUE THREAD

**Issue by GuoSirius** [lokesh/color-thief#179]
IE11 report TypeMismatchError Exception

here:
```js
var CanvasImage = function (image) {
    // in node we use strings as path to an image
    // whereas in the browser we use an image element
    if (iAmOnNode) {
      this.canvas = Canvas.createCanvas()
      var img = new Image;

      if(image instanceof Buffer) {
        img.src = image
      }else{
        img.src = fs.readFileSync(image);
      }

    } else {
      this.canvas = document.createElement('canvas');
      document.body.appendChild(this.canvas);
      var img = image;
    }

    this.context = this.canvas.getContext('2d');

    var width = img.width.baseVal ? img.width.baseVal.value : img.width;
    var height = img.height.baseVal ? img.height.baseVal.value : img.height;

    this.width  = this.canvas.width  = width;
    this.height = this.canvas.height = height;

    this.context.drawImage(img, 0, 0, this.width, this.height);
};
```

**Comment by lokesh** [comment]
The name of the package is `colorthief`, not `color-thief`. It's confusing.

This repo contains my original project. The original docs page is here: https://lokeshdhakar.com/projects/color-thief/

The fork which uses the `color-thief` npm name lives in this repo: https://github.com/null2/color-thief

I've contacted the owner of the color-thief npm package and am hoping for response so we can come up with a plan to reintegrate their fork to prevent confusion.

Last thing, I've added Node support to Color Thief. You don't need to use the null2 fork which requires some heavy, non-JS deps. Node support was added in v2.3.0:
https://github.com/lokesh/color-thief/releases

```
const { resolve } = require('path');
const ColorThief = require('colorthief');
const img = resolve(process.cwd(), 'night.jpg');

ColorThief.getColor(img)
	.then((color) => {
		console.log(color);
	})
```
