### ISSUE TITLE
typescript declaration file

### ISSUE THREAD

**Issue by MarchWorks** [lokesh/color-thief#188]
> Try `npm install @types/colorthief` if it exists or add a new declaration (.d.ts) file containing `declare module 'colorthief';`

unfortunately it doesn't exist

**Comment by grahamking** [comment]
Here's a  `colorthief.d.ts` that works for me. I put it in `src/types` and typescript picked it up automatically.

```
declare module 'colorthief' {
  type Color = [number, number, number];
  export default class ColorThief {
    getColor: (img: HTMLImageElement | null) => Color;
    getPalette: (img: HTMLImageElement | null) => Color[];
  }
}
```

**Comment by HeroadZ** [comment]
version with optional parameters:
```ts
declare module 'colorthief' {
    export type RGBColor = [number, number, number];
    export default class ColorThief {
        getColor: (img: HTMLImageElement | null, quality: number=10) => RGBColor;
        getPalette: (img: HTMLImageElement | null, colorCount: number=10, quality: number=10) => RGBColor[];
    }
}
```

**Comment by NatoBoram** [comment]
`getPalette` can return `null`

https://github.com/lokesh/color-thief/blob/master/src/color-thief.js#L96

**Comment by cabello** [comment]
This is what I've been using for over 4 months, create a file `colorthief.d.ts` in your source directory, a `d.ts` file only contains type definitions:

```typescript
declare module "colorthief" {
  export type RGBColor = [number, number, number]
  export default class ColorThief {
    getColor: (
      img: HTMLImageElement | null,
      quality: number = 10,
    ) => RGBColor | null

    getPalette: (
      img: HTMLImageElement | null,
      colorCount: number = 10,
      quality: number = 10,
    ) => RGBColor[] | null
  }
}
```

**Comment by Fasteroid** [comment]
Why closed the issue?  These are great type definitions here but I'd really love if they actually existed on the real package!

**Comment by pratikghare** [comment]
> ```ts
> declare module "colorthief" {
>   export type RGBColor = [number, number, number]
>   export default class ColorThief {
>     getColor: (
>       img: HTMLImageElement | null,
>       quality: number = 10,
>     ) => RGBColor | null
> 
>     getPalette: (
>       img: HTMLImageElement | null,
>       colorCount: number = 10,
>       quality: number = 10,
>     ) => RGBColor[] | null
>   }
> }
> ```

<img width="753" alt="image" src="https://github.com/user-attachments/assets/df7e7169-fcd9-45c5-8685-0f8d65876bca">

**Comment by aficus11** [comment]
this library is a slop lol
