### ISSUE TITLE
Cross Domain Images

### ISSUE THREAD

**Issue by bernatfortet** [lokesh/color-thief#20]
When I try to use an image hosted outside my server:

> Unable to get image data from canvas because the canvas has been tainted by cross-origin data. color-thief.js:50
> SecurityError: An attempt was made to break through the security policy of the user agent.

Is it possible to use Cross Domain images? 

Thank you very much.

**Comment by mhahmadi** [comment]
as long as the server serving the image provides the appropriate ```Allow-Control-Allow-Origin``` header, you should be able to do the following 

```javascript
var img = new Image();
img.onload = function () {
  var colorThief = new ColorThief();
  colorThief.getColor(img);
};
img.crossOrigin = 'Anonymous';
img.src = 'src of the image you want to process';
```

for testing purposes, using an extension like [this](https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?hl=en) should be easier than configuring the server

**Comment by glauberramos** [comment]
@mhahmadi solution worked for me

**Comment by geddski** [comment]
Thanks @mhahmadi for that temporary workaround! What a useful little extension.

**Comment by madprops** [comment]
> An easier solution is to add  to the image tag.

What do you mean?

**Comment by abiusx** [comment]
Huh it cut my attribute!

Adding `crossorigin='anonymous'` to the image tag!

**Comment by madprops** [comment]
That will only work with some hosts, and certain hosts will actually won't display the image when it's set to "anonymous". What I did in the end was host all the images myself.

**Comment by abiusx** [comment]
I mostly have had these issues with CDNs and external storage services like Amazon S3, and this has helped me on them.
Hosting the images on the server, or streaming through, is not a viable option due to extreme bandwidth.

**Comment by madprops** [comment]
What I do now is make the img have crossOrigin anonymous on every new image load, and if it fails to load, remove that attribute and try to load it again. This allows me to have linked images again :) 

The only disadvantage is that images without the attribute likely won't work with color-thief, but a lot of them will.

**Comment by lokesh** [comment]
An FAQ section has been added to the demo page that discusses x-domain CORS issues:
https://lokeshdhakar.com/projects/color-thief/#faq

Hope it helps. I'll continue fleshing it out as other use cases arrive.
