### ISSUE TITLE
Bug with the hook proccess  with react 17

### ISSUE THREAD

**Issue by hpachy** [lokesh/color-thief#200]
Hello I tried to use you color-thief-react but I still have this annoying error about react rules...
>Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
>1. You might have mismatching versions of React and the renderer (such as React DOM)
>2. You might be breaking the Rules of Hooks
>3. You might have more than one copy of React in the same app
>See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

<img width="1273" alt="Capture d’écran, le 2020-11-09 à 11 08 29" src="https://user-images.githubusercontent.com/24634810/98528164-38d98280-227c-11eb-9d20-5dc38c7bd277.png">

I wonder if you can help me to understand what's going on ....

I'm on react 17 and I'm using typeScript

**Comment by IyerChitra** [comment]
I'm facing the same issue. Even tried out the exact same code from the sample codesandbox. Doesn't seem to play nice with React 17 I think.
