### ISSUE TITLE
Facing error when 'npm install'

### ISSUE THREAD

**Issue by SSk123** [lokesh/color-thief#202]
I did ``rm-rf node_nodules`` and ``npm install`` in my root directory, I am facing this issue in colorthief package.

![image](https://user-images.githubusercontent.com/1384335/103070928-9df8f580-45e8-11eb-9371-ef33d8505dcd.png)

Within node_modules/colorthief/package.json there is a dependency getting loaded ``"quantize": "github:lokesh/quantize"``
which seems to be causing this error.

I am using ``node -v`` v12.16.1 and ``"colorthief": "^2.3.2"``
Any help in resolution is highly appreciated.

**Comment by Britt00** [comment]
I had the same issue. Currently using node v12.18.3. By downgrading to "colorthief": "^2.2.0" everything worked again. I did not try any other versions.

**Comment by BurntCaramel** [comment]
This also caused a problem for me. I believe publishing the fork `lokesh/quantize` as its own npm package would solve the problem, instead of referencing from github. I also had to downgrade to 2.2.0

**Comment by dreamerblue** [comment]
Please publish a npm package instead using `github:lokesh/quantize`. It will cause issues.

**Comment by taejs** [comment]
That needs fixing.

**Comment by aChudinov** [comment]
@lokesh Not it's a critical issue
https://github.blog/2021-09-01-improving-git-protocol-security-github/

**Comment by coldrainc** [comment]
Need publish quantize @lokesh

**Comment by forgowhisky** [comment]
still having this issue @lokesh

**Comment by pioug** [comment]
I created a monorepo with `colorthief` including some (abandoned) dependencies that needed an update too. It's not super classy to share it here but we are losing so much time collectively trying to fix this. Please head over to https://github.com/pioug/colorsuite, if anyone is interested in keeping the project/repository alive, ping me there, I'll add you as a maintainer.

```
npm install colorthief@npm:@pioug/colorthief
```

**Comment by lokesh** [comment]
The install issues with the quantize dep were resolved in early 2023. Sorry for the hiccups.
