### ISSUE TITLE
"Uncaught ReferenceError: i is not defined at n.onload" when calling getImageData

### ISSUE THREAD

**Issue by jcgjunge** [lokesh/color-thief#221]
There seems to be an error in the function getImageData. 

The line "i = uInt8Array.length;" is giving the error "Uncaught ReferenceError: i is not defined at n.onload". Since it does not really do anything the line should be deleted.

https://github.com/lokesh/color-thief/blob/ef231c711309dc32be1efa83bd4da7c0ed21cd6e/src/color-thief.js#L120

**Comment by lokesh** [comment]
Closing old iss
