### ISSUE TITLE
github.com/lokesh/quantize.git

### ISSUE THREAD

**Issue by hituraj** [lokesh/color-thief#225]
node version = v16.17.1 & npm version = 8.15.0..Don't want to downgrade the node & npm version

19:22:28 npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/lokesh/quantize.git
19:22:28 npm ERR! ssh: connect to host github.com port 22: No route to host
19:22:28 npm ERR! fatal: Could not read from remote repository.

@lokesh

**Comment by nirajsharma99** [comment]
Hey am facing the same error in both the new and older npm versions.
Hey @lokesh can you please kindly help us with this issue.

Thanks :)

**Comment by lokesh** [comment]
The quantize install issue should be resolved now.

The package is on npmjs.com now:
https://www.npmjs.com/package/@lokesh.dhakar/quantize

The latest release of color-thief updates the quantize dep reference in package.json:
https://github.com/lokesh/color-thief/releases/tag/v2.4.0
