### ISSUE TITLE
There seems to be some writing problems with the documentation

### ISSUE THREAD

**Issue by Chairowell** [lokesh/color-thief#226]
![image](https://user-images.githubusercontent.com/64683147/195963758-e9e7dfc5-0e05-4ead-b275-fdf2c9df4034.png)

### Should be changed to
`img.addEventListener('load', function() {
  colorThief.getColor(img);
});`

**Comment by lokesh** [comment]
Fixed. Thanks!

https://lokeshdhakar.com/projects/color-thief/
