### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by bmarti44** [lokesh/color-thief#228]
It looks like no PRs have been merged and no (meaningful) issues resolved for around two years... Is this project still maintained?

**Comment by adriaanvanrossum** [comment]
Probably not. It would also be awesome to have request removed:

<img width="714" alt="image" src="https://user-images.githubusercontent.com/1079135/214051515-60c70833-a41f-401b-93d2-80318b074c3e.png">

https://npmgraph.js.org/?q=color-extr-thief

**Comment by adriaanvanrossum** [comment]
<img width="894" alt="image" src="https://user-images.githubusercontent.com/1079135/217153720-d7ddaaf0-7b7e-4852-920e-c4391dd81db8.png">

**Comment by lokesh** [comment]
My maintenance efforts have been spotty. I recently brought in some big fixes and dep upgrades but do not have plans for any major feature updates.
