### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by ninadsutrave** [lokesh/color-thief#229]
I wanted to try out the utility in a Node project however I am unable to install the package. Is the service no longer running? It just says that 'this library is no longer supported'.

**Comment by Psycomentis06** [comment]
It looks like I used it 3 years ago. but now it doesn't. If you want to use it you can fork it and update the library and upgrade it to a newer node version.

**Comment by NinadSutrave** [comment]
Can I submit a pr after making the necessary updates? Asking because I don't see any merges lately.

**Comment by lokesh** [comment]
Give the latest version a go which was released recently. It should resolve the install issues related to the quantize dep reference in package.json:
https://github.com/lokesh/color-thief/releases/tag/v2.4.0

Let me know if the issue persists for you and I'll reopen.
