### ISSUE TITLE
Trying to get it work

### ISSUE THREAD

**Issue by onigetoc** [lokesh/color-thief#23]
I want to get color palette when i click a image. i don't know how to make it work, what should be the value of : sourceImage

image src? all image tag?

The documentation is too minimalist

Nothing work

**Comment by althe3rd** [comment]
Thank you so much Simonseddon for the mention on how to grab the img element. I have been banging my head against the keyboard for hours trying to figure out why the script claims I wasn't giving it an image when I selected it using $("img").first(); in jQuery.

**Comment by pierrebonbon** [comment]
Thanks simonseddon for the last note. I was having a hard time converting the returned R,G,B into Hex. It came to my mind that perhaps the returned value was actually an array, not a string, and I had to iterate through it to get my function going, but didn't came to mind that I could do it this way: c[0],c[1],c[3]. Your little note saved me quite a lot of time!

**Comment by zamartz** [comment]
pierrebonbon - I created a pull request for HEX conversion here: https://github.com/lokesh/color-thief/pull/78
should give you the gist

**Comment by lokesh** [comment]
The demo page documentation has been extended with an API table and more examples:
https://lokeshdhakar.com/projects/color-thief/

Hope it helps. I'll continue to flesh out as new questions arrive.
