### ISSUE TITLE
Getting security vulnerability due to get-pixels

### ISSUE THREAD

**Issue by somyarocketium** [lokesh/color-thief#246]
Any better approach to fix this vulnerability ? 

┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ tough-cookie Prototype Pollution vulnerability               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ tough-cookie                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.1.3                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ colorthief                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ colorthief > get-pixels > request > tough-cookie             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://github.com/advisories/GHSA-72xf-g2v4-qvf3            │
└───────────────┴──────────────────────────────────────────────────────────────┘

**Comment by Yoda-Soda** [comment]
bump

**Comment by briandonahue** [comment]
@Yoda-Soda @somyarocketium I submitted #254 but thought I'd tag you in case you wanted to check it out and/or provide feedback.  Seems like a viable approach if we want to be able to use `color-thief`

**Comment by lokesh** [comment]
Resolved in https://github.com/lokesh/color-thief/releases/tag/v2.6.0

Thanks to @briandonahue
