### ISSUE TITLE
is there a way to get the most common color, not the averaged dominant color?

### ISSUE THREAD

**Issue by l0c0luke** [lokesh/color-thief#26]

**Comment by glauberramos** [comment]
+ 1

**Comment by Pluto1010** [comment]
How is the "most common" color defined in contract to the dominant color?

**Comment by lokesh** [comment]
The _most common color_ is actually different than the _dominant_ color as far as this script goes.

Color Thief uses the median cut algorithm provided by `quantize.js` to cluster similar colors and return the base color from the largest cluster. This becomes the dominant color.

I originally tried grabbing the most common color in the image but found that it mostly returned a muddy gray color when used with photos. This color didn't line up with I perceived as the dominant color in the photo.
