### ISSUE TITLE
Quality less than 1 causes infinite loop.

### ISSUE THREAD

**Issue by nteike** [lokesh/color-thief#32]
In the comments it is written that "0 is the highest quality settings". Quality settings below 1 will always cause infinite loops: 

```
 for (var i = 0, offset, r, g, b, a; i < pixelCount; i = i + quality) {
```

I propose to change the validation:

```
if (typeof quality === 'undefined' || quality < 1) {
        quality = 10;
    }
```

**Comment by lokesh** [comment]
#33 merged
