### ISSUE TITLE
Update 'main' attribute in bower.json

### ISSUE THREAD

**Issue by hitchcockwill** [lokesh/color-thief#41]
The 'main' attribute in the `bower.json` file currently points to a file that does not exist.

Should be `dist/color-thief.min.js` or `src/color-thief.js`

**Comment by johngeorgewright** [comment]
Until it's merged you can use overrides:

```json
{
  "dependencies": {
    "color-thief": "~2.0.0"
  },
  "overrides": {
    "color-theif": {
      "main": "src/color-thief.js"
    }
  }
}
```
