### ISSUE TITLE
Simple example please

### ISSUE THREAD

**Issue by th3lonius** [lokesh/color-thief#43]
I would love to put this plugin to use on a project right now but I can't figure it out. I know a call for better documentation has been made in other requests but I would like to just ask for a simple example from someone who has made this work. I just want to extract the dominant rgb values from an image and use that to alter the background color of another element. I only need to use the first image on a page so I can target it like so: $('body > .target-image')

I am a javascript novice and my attempts to decipher the demo.js have failed. Please and thank you for any help!

p.s. And thank you for making this Lokesh! I have searched quite a bit and can find nothing else out there that does this (at least not using jQuery anyway). Help me figure it out so I can use it please!

**Comment by bianjp** [comment]
Meet the same problem.
Solve it by
```javascript
var image = document.querySelector('.target-image');
image.onload = function(){
    var colorThief = new ColorThief();
    var color = colorThief.getColor(image); 
};
```

**Comment by cemerson** [comment]
I had to wrap this in a window.Timeout() delay to get it working now (7/6/2019).
`window.setTimeout(function(){
    var colorThief = new ColorThief();
    var color = colorThief.getColor(image,25); 
},1500);`

**Comment by lokesh** [comment]
Added a FAQ section in the docs to cover this issue concerning the image not being loaded:
https://lokeshdhakar.com/projects/color-thief/#faq

@cemerson rather than a setTimeout, try doing the following:
```
const colorThief = new ColorThief();
let img = document.querySelector('img');

if (image.complete) {
  colorThief.getColor(img, 25);
} else {
  image.addEventListener('load', function() {
    colorThief.getColor(image, 25);
  });
}

```

**Comment by madmacc** [comment]
> Added a FAQ section in the docs to cover this issue concerning the image not being loaded: https://lokeshdhakar.com/projects/color-thief/#faq
> 
> @cemerson rather than a setTimeout, try doing the following:
> 
> ```js
> const colorThief = new ColorThief();
> let img = document.querySelector('img');
> 
> if (image.complete) {
>   colorThief.getColor(img, 25);
> } else {
>   image.addEventListener('load', function() {
>     colorThief.getColor(image, 25);
>   });
> }
> ```

This worked for me.  I was getting the same error:
```
Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source
width is 0.
```
Strange as I was running the code after 10s so the image was definitely loaded.
