### ISSUE TITLE
Using semver tags

### ISSUE THREAD

**Issue by simonc** [lokesh/color-thief#52]
Hi :)

Unlike stated in issue #15 tags are not following semver (`2.0` instead of `2.0.0`). It prevents using tools like [rails-assets](https://rails-assets.org) that depend on semver tags.

Would it be possible to use complete version number git tags?

Thanks! :)

**Comment by gustavohenke** [comment]
:+1: for this.

Running `bower info color-thief` returns `No versions available.`.

**Comment by Sly777** [comment]
+1

**Comment by lokesh** [comment]
Since this issue was created, the project has switched to using properly formatted semver tags:
- https://github.com/lokesh/color-thief/blob/master/package.json#L3
- https://github.com/lokesh/color-thief/releases

Bower support was dropped.
