### ISSUE TITLE
MMCQ.quantize(...) can return false or undefined thus breaking the application.

### ISSUE THREAD

**Issue by mhahmadi** [lokesh/color-thief#54]
cmap can become false or undefined after the following statement causing ```cmap.palette() ``` in the next line to throw an error.
```javascript
var cmap = MMCQ.quantize(pixelArray, colorCount);
```

it can be prevented with the following check and perhaps the return value can be null in such situation:

```javascript
var cmap = MMCQ.quantize(pixelArray, colorCount);
var palette = cmap? cmap.palette() : null;
```

**Comment by lokesh** [comment]
#55 merged. Thanks again.
