### ISSUE TITLE
 for colorCount < 2  or colorCount > 256

### ISSUE THREAD

**Issue by mhahmadi** [lokesh/color-thief#56]
`MMCQ.quantize(...)` returns false for those values leading to calling `palette()` on false in the next statement which throws an error. perhaps the validation can change to the following:

``` javascript
if (typeof colorCount === 'undefined' || colorCount < 2 || colorCount > 256) {
    colorCount = 10;
}
```

**Comment by lokesh** [comment]
Better late than never. Merged your PR. Thanks for the contribution.

I'll do a bit more testing before putting out the new release.
