### ISSUE TITLE
Error on Gif Images?

### ISSUE THREAD

**Issue by jdmagic21** [lokesh/color-thief#61]
I get the following error in my console window when working with Gif images. Any reason why? 

Uncaught TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(HTMLImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap)'

**Comment by gutierrezfredo** [comment]
Im getting this error too... any help please????

**Comment by mbejda** [comment]
Some more code would be helpful. Are you passing it in as an html element?
```
		var imgObj = new Image();
		imgObj.src='/images/yeoman.png';
		var colorThief = new ColorThief();
		var colors = colorThief.getPalette(imgObj, 8);
```

**Comment by lokesh** [comment]
Closing out old issues.

I was never able to recreate the issue reported. If someone can provide details steps to recreate I will open and investigate further. Thanks!
