### ISSUE TITLE
Bower.json has incorrect "main" property breaking automated builds

### ISSUE THREAD

**Issue by drmunklung** [lokesh/color-thief#67]
Your bower.json file has an incorrect path in the "main" property. This breaks automated script injection via Grunt and Gulp. Currently it's set to:

``` javascript
"main": "js/color-thief.js",
```

It should be:

``` javascript
    "main": "src/color-thief.js"
```

Otherwise, this is an awesome utility,
Thanks!

**Comment by lokesh** [comment]
Bower support has since been dropped because of decreasing popularity and project inactivity.
