### ISSUE TITLE
Building Canvas@1.1.2

### ISSUE THREAD

**Issue by cataquil** [lokesh/color-thief#69]
Is there a way to build this with NPM without having to build canvas, since it calls python and visual studio

**Comment by rayronvictor** [comment]
+1

**Comment by lokesh** [comment]
Closing out this older issue. This is describing the challenge of installing the deps for using Color Thief in a Node env with null2's fork of the project: https://github.com/null2/color-thief

I'm investigating adding Node support to the mainline of this project (this repo) w/o the heavy deps.
