### ISSUE TITLE
Canvas is appended to body, leaves image if an error occurs.

### ISSUE THREAD

**Issue by Luke-SF** [lokesh/color-thief#75]
I noticed the script appends canvas to document.body element... Why?

document.body.appendChild(this.canvas)

If there's an error such as Uncaught SecurityError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D' it leaves the image at bottom of the page.

**Comment by jlabresh1** [comment]
I noticed this too. +1 to this

**Comment by bubbafoley** [comment]
+1

**Comment by rafgeekee** [comment]
+1

**Comment by lokesh** [comment]
This issue was eventually resolved. Color Thief now does not append the `<canvas>` tag to the DOM: https://github.com/lokesh/color-thief/pull/150/files
