### ISSUE TITLE
Preventing duplicate colours in a palette

### ISSUE THREAD

**Issue by Dayjo** [lokesh/color-thief#77]
Hello, 

I'm having fun with color-thief, but does anyone have a solution to not include duplicate colours in the palette? Is there any reason to ever include duplicates?

For instance for one image and set to get 100 colours, it returns this;
![](http://c.dayjo.me/image/3g1v1D3M3J2a/Image%202015-07-26%20at%201.55.56%20pm.png)
Where the majority of the colours at the bottom are exactly the same.

I suppose this could also be seen as changing the `colorCount` to act more like `maximumColors`. It seems like maybe it just back fills the rest of the colours with the last one it found?

I was looking to implement this functionality but was unsure whether it should be part of the getPalette function or the quantize function. Happy to give it a bash if anyone has any suggestions?

**Comment by rafaelrinaldi** [comment]
@Dayjo This definitely belongs to `getPalette` IMO.

**Comment by lokesh** [comment]
Reviewing issues posted that are related to the color quantization algorithm. If anyone else has seen similar issues, please post the source image and I will review. Thanks.
