### ISSUE TITLE
Update license in color-thief.js and color-thief.min.js header

### ISSUE THREAD

**Issue by mortenson** [lokesh/color-thief#80]
While the main LICENSE file in this repo has been changed to MIT, the headers on color-thief.js still use Creative Commons Attribution 2.5. This makes the actual licensing on this codebase a bit confusing. :)

Could the maintainer change the license in the headers to MIT? Thanks!

**Comment by brantwynn** [comment]
Hi, this is preventing us from making a release of our packaged drupal distribution that contains color thief. Would a pull request help?

**Comment by lokesh** [comment]
Fixed in v2.0.1. MIT all-around now!

https://github.com/lokesh/color-thief/releases
[Commit](https://github.com/lokesh/color-thief/commit/36a3c4171e9564f12fa6cc86389b2299554ca68f?diff=unified)
