### ISSUE TITLE
Automate this with a large collection of images?

### ISSUE THREAD

**Issue by jschell42** [lokesh/color-thief#82]
Any suggestions on how to automate this with a set of 300+ (or more) images? I'm looking to use this to sort the images (which are album covers) by color. Thanks!

**Comment by rafaelrinaldi** [comment]
@jschell42 I think that handling multiple images is out of the scope of this library.

For your problem you might try to loop through all the images and delegate the color pallete solving to an async function? [Promises](https://developer.mozilla.org/en-US/Add-ons/Techniques/Promises) can help you with this.
If you want help, please provide us with some code sample.

**Comment by lokesh** [comment]
Closing out old issues with not recent activity.

Re: automating this across a large set of images
For a large number of images you should do the palette generation ahead of time. You could use color thief with phantomjs on the server, but at that point you should also investigate other serve side options that are more performant.
