### ISSUE TITLE
Detect second dominate color? (e.g. Girl w/ Dress, detects skin color not dress)

### ISSUE THREAD

**Issue by DylanOpet** [lokesh/color-thief#93]
Possible to detect second dominate color? Majority detect the skin color before the dress as the dominate, would be AMAZING for fashion eCommerce and work wonderful. I'm building a widget to work with Shopify/etc/etc to detect dominate color then make it a variant option with that exact color for color attribute selection when picking a product. I'll be releasing open-source too!

![blue](https://cloud.githubusercontent.com/assets/1181721/12634295/72fb43c6-c535-11e5-8ff8-a26e7eef0dda.jpg)

**Comment by Pluto1010** [comment]
I've written an exension that returns the most intense color from a palette returned by ColorThief. Does this help? I'm not sure if its right for your use-case.

Have a look at https://gist.github.com/Pluto1010/f26beed7fdebfb2e2110

**Comment by ShaggyDude** [comment]
I am trying to convert the rgb to hex output. The above plugin may help me get it working. I am guessing the -boom.js is loaded after the color-thief.js?

**Comment by DylanOpet** [comment]
@Pluto1010 Oooh, going to dabble with this. Cheers mate.

@ShaggyDude Yes, I would totally assume so!

**Comment by lokesh** [comment]
You can also fetch a palette view the `getPalette` method but limit the color count to 2. Unfortunately, setting the color count to 2, most often returns 3 colors. :-/ I'm looking into this bug actively.

Here is the results of the image posted above run with `colorThief.getPalette(image, 2);`:

![image](https://cloud.githubusercontent.com/assets/51469/20045587/4207b63a-a457-11e6-938d-60ab128b8823.png)
