### ISSUE TITLE
Option to downsize?

### ISSUE THREAD

**Issue by Luke-SF** [lokesh/color-thief#97]
Seems there should be an option to initialized Colorthief with a downsized image, maybe even a default max for its working canvas. Otherwise it crashes with IndexError for a huge (say 3mp) image.

**Comment by lokesh** [comment]
There is an optional `quality` argument that let's you reduce the number of pixels processed by the script. For large images this could be handy. I would try numbers above 10. Example: `colorThief.getPalette(image, 10, 50)`

```js
getPalette(sourceImage[, colorCount, quality])
returns [ [num, num, num], [num, num, num], ... ]
```
